name: Build Synology Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dsm: ["7.2"]
        arch: ["noarch"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Synology Package
        uses: ./.
        with:
          dsm: ${{ matrix.dsm }}
          arch: ${{ matrix.arch }}
          projects: 'src/mypackage'
          output: './dist'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: synology-package-${{ matrix.dsm }}-${{ matrix.arch }}
          path: ./dist/*.spk
